# Generated by Django 5.2.6 on 2025-12-02 11:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("apikey", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("session_id", models.CharField(db_index=True, max_length=100)),
                (
                    "campaign_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("utm_id", models.CharField(blank=True, default="", max_length=255)),
                ("first_event", models.DateTimeField()),
                ("last_event", models.DateTimeField()),
                ("conversion_event", models.DateTimeField(blank=True, null=True)),
                ("last_processed_at", models.DateTimeField(blank=True, null=True)),
                ("events", models.JSONField(blank=True, default=list)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("device_type", models.CharField(default="desktop", max_length=50)),
                ("country", models.CharField(blank=True, default="", max_length=100)),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                ("state", models.CharField(blank=True, default="", max_length=100)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("location_accuracy", models.FloatField(blank=True, null=True)),
                (
                    "location_source",
                    models.CharField(default="ip_geolocation", max_length=50),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("processing", "Processing"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "total_emissions_g",
                    models.FloatField(default=0.0, help_text="Total CO2e in grams"),
                ),
                (
                    "emissions_breakdown",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Detailed emission breakdown",
                    ),
                ),
                (
                    "api_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="apikey.apikey",
                    ),
                ),
            ],
            options={
                "db_table": "sessions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["session_id", "api_key"],
                        name="sessions_session_e6a21f_idx",
                    ),
                    models.Index(
                        fields=["campaign_id"], name="sessions_campaig_196cf1_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="sessions_created_0a2de2_idx"
                    ),
                    models.Index(fields=["utm_id"], name="sessions_utm_id_1f578b_idx"),
                    models.Index(
                        fields=["status", "last_event"],
                        name="sessions_status_4c11c8_idx",
                    ),
                ],
                "unique_together": {("session_id", "api_key")},
            },
        ),
    ]
