
# Generated by Django 5.2.6 on 2025-12-23 07:46

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apikey", "0002_apikey_industry_type"),
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarbonBalance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "user_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "total_emissions_kg",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "balance_kg",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                ("last_transaction_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Carbon Balance",
                "verbose_name_plural": "Carbon Balances",
                "db_table": "carbon_balances",
            },
        ),
        migrations.CreateModel(
            name="CarbonTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("user_id", models.CharField(db_index=True, max_length=255)),
                ("transaction_type", models.CharField(max_length=20)),
                ("amount_kg", models.DecimalField(decimal_places=6, max_digits=20)),
                (
                    "balance_before",
                    models.DecimalField(decimal_places=6, max_digits=20),
                ),
                ("balance_after", models.DecimalField(decimal_places=6, max_digits=20)),
                ("reference_id", models.CharField(db_index=True, max_length=255)),
                ("reference_type", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "carbon_transactions",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ProcessedEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference_id", models.CharField(db_index=True, max_length=255)),
                ("reference_type", models.CharField(db_index=True, max_length=100)),
                ("user_id", models.CharField(db_index=True, max_length=255)),
                (
                    "session_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                ("event_data", models.JSONField(blank=True, default=dict)),
                (
                    "kg_co2_emitted",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                ("event_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "processed_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "processed_events",
                "ordering": ["-processed_at"],
            },
        ),
        migrations.RemoveIndex(
            model_name="session",
            name="sessions_created_0a2de2_idx",
        ),
        migrations.RemoveIndex(
            model_name="session",
            name="sessions_utm_id_1f578b_idx",
        ),
        migrations.RemoveField(
            model_name="session",
            name="events",
        ),
        migrations.RemoveField(
            model_name="session",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="session",
            name="location_accuracy",
        ),
        migrations.RemoveField(
            model_name="session",
            name="location_source",
        ),
        migrations.RemoveField(
            model_name="session",
            name="longitude",
        ),
        migrations.AddField(
            model_name="session",
            name="event_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="session",
            name="events_summary",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Summary: {page_views: 10, conversions: 2}",
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="user_id",
            field=models.CharField(db_index=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="session",
            name="utm_params",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="session",
            name="emissions_breakdown",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="session",
            name="last_event",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="last_processed_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("closed", "Closed"),
                ],
                db_index=True,
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["user_id", "status"], name="sessions_user_id_40f7d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["status", "last_processed_at"],
                name="sessions_status_a2ff5b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="carbontransaction",
            index=models.Index(
                fields=["user_id", "timestamp"], name="carbon_tran_user_id_226e7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carbontransaction",
            index=models.Index(
                fields=["reference_id", "reference_type"],
                name="carbon_tran_referen_866e2e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="carbontransaction",
            index=models.Index(
                fields=["transaction_type", "timestamp"],
                name="carbon_tran_transac_fd384e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="processedevent",
            index=models.Index(
                fields=["user_id", "processed_at"],
                name="processed_e_user_id_3dd949_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="processedevent",
            index=models.Index(
                fields=["session_id", "processed_at"],
                name="processed_e_session_785e4d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="processedevent",
            index=models.Index(
                fields=["event_type", "processed_at"],
                name="processed_e_event_t_f20aea_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="processedevent",
            index=models.Index(
                fields=["reference_type", "processed_at"],
                name="processed_e_referen_3f30aa_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="processedevent",
            unique_together={("reference_id", "reference_type")},
        ),
    ]
