# Generated by Django 5.2.6 on 2025-12-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_carbonbalance_carbontransaction_processedevent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActiveSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("user_id", models.CharField(db_index=True, max_length=255)),
                ("api_key", models.CharField(db_index=True, max_length=255)),
                ("last_event_at", models.DateTimeField(auto_now=True)),
                ("event_count", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(db_index=True, default="active", max_length=20),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "active_sessions",
                "ordering": ["-last_event_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "last_event_at"],
                        name="active_sess_status_65ead7_idx",
                    ),
                    models.Index(
                        fields=["user_id", "status"],
                        name="active_sess_user_id_5f8e4d_idx",
                    ),
                ],
            },
        ),
    ]
