# Generated by Django 5.2.8 on 2025-11-28 07:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('phonenumber', models.TextField(blank=True, db_column='phoneNumber', null=True)),
                ('companyname', models.TextField(blank=True, db_column='companyName', null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedat', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('otpcode', models.TextField(blank=True, db_column='otpCode', null=True)),
                ('otpexpiry', models.DateTimeField(blank=True, db_column='otpExpiry', null=True)),
                ('otpverified', models.BooleanField(db_column='otpVerified', default=False)),
                ('isactive', models.BooleanField(db_column='isActive', default=True)),
                ('onboarded', models.BooleanField(db_column='onboarded', default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
    ]
