# Generated by Django 5.2.8 on 2025-12-01 13:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('linkedin', 'LinkedIn'), ('google_ads', 'Google Ads'), ('meta_ads', 'Meta Ads')], max_length=32)),
                ('provider_user_id', models.TextField()),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_auth.user')),
            ],
            options={
                'db_table': 'credential',
                'managed': True,
                'unique_together': {('provider', 'provider_user_id')},
            },
        ),
    ]
