# Generated by Django 5.2.6 on 2025-12-23 07:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_auth", "0004_credential"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="credential",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="credential",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="credential",
            name="extras",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional provider-specific metadata",
            ),
        ),
        migrations.AddField(
            model_name="credential",
            name="scopes",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated list of granted scopes",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="credential",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(default=1, max_length=128, verbose_name="password"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="credential",
            name="access_token",
            field=models.TextField(help_text="OAuth access token for API calls"),
        ),
        migrations.AlterField(
            model_name="credential",
            name="expires_at",
            field=models.DateTimeField(
                blank=True, help_text="Token expiration timestamp", null=True
            ),
        ),
        migrations.AlterField(
            model_name="credential",
            name="provider",
            field=models.CharField(
                choices=[
                    ("linkedin", "LinkedIn"),
                    ("google_ads", "Google Ads"),
                    ("meta_ads", "Meta Ads"),
                    ("dv360", "Display & Video 360"),
                    ("tiktok", "TikTok"),
                    ("snapchat", "Snapchat"),
                    ("twitter_x", "Twitter/X"),
                ],
                help_text="OAuth provider (Google Ads, Meta, LinkedIn, etc.)",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="credential",
            name="provider_user_id",
            field=models.TextField(help_text="User ID from the provider's system"),
        ),
        migrations.AlterField(
            model_name="credential",
            name="refresh_token",
            field=models.TextField(
                blank=True,
                help_text="OAuth refresh token for renewing access",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="credential",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credentials",
                to="custom_auth.user",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="onboarded",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="credential",
            unique_together={("user", "provider", "provider_user_id")},
        ),
        migrations.AddIndex(
            model_name="credential",
            index=models.Index(
                fields=["user", "provider"], name="credentials_user_id_1c6363_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="credential",
            index=models.Index(
                fields=["provider", "provider_user_id"],
                name="credentials_provide_cff4c2_idx",
            ),
        ),
        migrations.AlterModelTable(
            name="credential",
            table="credentials",
        ),
        migrations.AlterModelTable(
            name="user",
            table="users",
        ),
    ]
