# Generated by Django 5.2.6 on 2025-12-02 06:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("user_id", models.CharField(db_index=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("usage_count", models.IntegerField(default=0)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("domain", models.CharField(default="*", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "api_keys",
                "indexes": [
                    models.Index(
                        fields=["user_id"], name="api_keys_user_id_1863c8_idx"
                    ),
                    models.Index(fields=["key"], name="api_keys_key_291dcc_idx"),
                    models.Index(
                        fields=["is_active"], name="api_keys_is_acti_73be43_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ConversionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("url", "URL Match"),
                            ("click", "Element Click"),
                            ("form_submit", "Form Submission"),
                            ("custom_event", "Custom Event"),
                        ],
                        default="url",
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "url_pattern",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("exact", "Exact Match"),
                            ("contains", "Contains"),
                            ("starts_with", "Starts With"),
                            ("ends_with", "Ends With"),
                            ("regex", "Regular Expression"),
                            ("query_param", "Query Parameter"),
                        ],
                        default="contains",
                        max_length=50,
                    ),
                ),
                (
                    "css_selector",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "element_text",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("form_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "custom_event_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("track_value", models.BooleanField(default=False)),
                (
                    "value_selector",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "default_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("priority", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("conversion_count", models.IntegerField(default=0)),
                ("last_triggered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "api_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversion_rules",
                        to="apikey.apikey",
                    ),
                ),
            ],
            options={
                "db_table": "conversion_rules",
                "ordering": ["-priority", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["api_key", "is_active"],
                        name="conversion__api_key_a34168_idx",
                    ),
                    models.Index(
                        fields=["rule_type"], name="conversion__rule_ty_a76e5b_idx"
                    ),
                    models.Index(
                        fields=["priority"], name="conversion__priorit_864483_idx"
                    ),
                ],
            },
        ),
    ]
