# Generated by Django 5.2.6 on 2025-12-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apikey", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="industry_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
