# Generated by Django 5.2.6 on 2025-12-24 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apikey", "0002_apikey_industry_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Industry",
                "verbose_name_plural": "Industries",
                "db_table": "industries",
                "ordering": ["category__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="IndustryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Industry Category",
                "verbose_name_plural": "Industry Categories",
                "db_table": "industry_categories",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="apikey",
            name="industry",
            field=models.ForeignKey(
                blank=True,
                help_text="Industry for emission calculations",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="api_keys",
                to="apikey.industry",
            ),
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(fields=["industry"], name="api_keys_industr_c686ca_idx"),
        ),
        migrations.AddField(
            model_name="industry",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="industries",
                to="apikey.industrycategory",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="industry",
            unique_together={("category", "name")},
        ),
    ]
