# Generated by Django 5.2.6 on 2025-12-24 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apikey", "0004_alter_industry_unique_together_and_more"),
    ]

    # operations = [
    #     migrations.RemoveIndex(
    #         model_name="apikey",
    #         name="api_keys_industr_c686ca_idx",
    #     ),
    # ]
