# Generated by Django 5.2.6 on 2025-12-24 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apikey", "0005_remove_apikey_api_keys_industr_c686ca_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="apikey",
            name="api_keys_industr_c686ca_idx",
        ),
    ]
