# Generated by Django 5.2.6 on 2025-12-24 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apikey", "0006_remove_apikey_api_keys_industr_c686ca_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="apikey",
            name="api_keys_industr_804a92_idx",
        ),
        migrations.RemoveIndex(
            model_name="apikey",
            name="api_keys_product_b11e82_idx",
        ),
        migrations.RemoveField(
            model_name="apikey",
            name="industry_category",
        ),
        migrations.RemoveField(
            model_name="apikey",
            name="product",
        ),
    ]
