# Generated by Django 5.2.6 on 2025-12-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apikey", "0007_remove_apikey_api_keys_industr_804a92_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="industry_category",
            field=models.CharField(
                blank=True,
                choices=[("internet", "Internet"), ("oil_and_gas", "Oil and Gas")],
                help_text="Industry category for the API key",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="apikey",
            name="product",
            field=models.CharField(
                blank=True,
                choices=[("ads", "Ads"), ("web", "Web"), ("lubricant", "Lubricant")],
                help_text="Product within the industry category",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(
                fields=["industry_category"], name="api_keys_industr_804a92_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(fields=["product"], name="api_keys_product_b11e82_idx"),
        ),
    ]
