# Generated by Django 5.2.6 on 2025-12-24 09:51

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("custom_auth", "0005_alter_credential_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "google_ads_campaign_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "google_ads_customer_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                ("total_impressions", models.BigIntegerField(default=0)),
                ("total_clicks", models.BigIntegerField(default=0)),
                ("total_cost_micros", models.BigIntegerField(default=0)),
                (
                    "total_emissions_kg",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=15
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="campaigns",
                        to="custom_auth.user",
                    ),
                ),
            ],
            options={
                "db_table": "campaigns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignEmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("hour", models.IntegerField(blank=True, null=True)),
                (
                    "country",
                    models.CharField(
                        db_index=True, default="United States", max_length=100
                    ),
                ),
                ("region", models.CharField(blank=True, default="", max_length=100)),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                (
                    "device_type",
                    models.CharField(db_index=True, default="desktop", max_length=50),
                ),
                ("page_views", models.IntegerField(default=0)),
                ("clicks", models.IntegerField(default=0)),
                ("conversions", models.IntegerField(default=0)),
                ("sessions", models.IntegerField(default=0)),
                ("impressions", models.BigIntegerField(default=0)),
                ("ad_clicks", models.BigIntegerField(default=0)),
                ("cost_micros", models.BigIntegerField(default=0)),
                (
                    "impression_emissions_g",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=15
                    ),
                ),
                (
                    "page_view_emissions_g",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=15
                    ),
                ),
                (
                    "click_emissions_g",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=15
                    ),
                ),
                (
                    "conversion_emissions_g",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=15
                    ),
                ),
                (
                    "total_emissions_g",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=15
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emissions",
                        to="campaign.campaign",
                    ),
                ),
            ],
            options={
                "db_table": "campaign_emissions",
                "ordering": ["-date", "-hour"],
            },
        ),
        migrations.CreateModel(
            name="UTMParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True, default="utm_source", max_length=50
                    ),
                ),
                ("value", models.CharField(db_index=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utm_params",
                        to="campaign.campaign",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="utm_parameters",
                        to="custom_auth.user",
                    ),
                ),
            ],
            options={
                "db_table": "utm_parameters",
            },
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["user", "google_ads_customer_id"],
                name="campaigns_user_id_607262_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["google_ads_campaign_id"], name="campaigns_google__d5e9be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["is_archived"], name="campaigns_is_arch_5bbee5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["-created_at"], name="campaigns_created_163163_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("google_ads_campaign_id__isnull", False),
                    ("google_ads_customer_id__isnull", False),
                ),
                fields=("user", "google_ads_campaign_id", "google_ads_customer_id"),
                name="unique_user_google_campaign",
            ),
        ),
        migrations.AddIndex(
            model_name="campaignemission",
            index=models.Index(
                fields=["campaign", "date"], name="campaign_em_campaig_e83f9a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaignemission",
            index=models.Index(
                fields=["country", "date"], name="campaign_em_country_41c82a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaignemission",
            index=models.Index(
                fields=["device_type", "date"], name="campaign_em_device__f87ddb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaignemission",
            index=models.Index(
                fields=["date", "hour"], name="campaign_em_date_ee20c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaignemission",
            index=models.Index(fields=["-date"], name="campaign_em_date_ae58ee_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="campaignemission",
            unique_together={
                ("campaign", "date", "hour", "country", "region", "device_type")
            },
        ),
        migrations.AddIndex(
            model_name="utmparameter",
            index=models.Index(
                fields=["campaign", "key"], name="utm_paramet_campaig_ce82f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="utmparameter",
            index=models.Index(fields=["value"], name="utm_paramet_value_5ebeb3_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="utmparameter",
            unique_together={("campaign", "key")},
        ),
    ]
